version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: lumira-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lumira
      MONGO_INITDB_ROOT_PASSWORD: lumira2024
      MONGO_INITDB_DATABASE: oracle-lumira
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - lumira-network

  # Oracle Lumira Frontend
  app:
    build: .
    container_name: lumira-app
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - lumira-network

  # n8n Automation (Optional - can be deployed separately)
  n8n:
    image: n8nio/n8n:latest
    container_name: lumira-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=lumiran8n2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.oraclelumira.com
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - lumira-network

volumes:
  mongo_data:
    driver: local
  n8n_data:
    driver: local

networks:
  lumira-network:
    driver: bridge
